dist: focal

addons:
  apt:
    packages:
      - curl
      - make
      - gzip

language: bash

services:
  - docker

script:
  - echo "start script"
  - WORK_DIR=$(pwd)
  - cd /tmp
  - curl https://cdn.azul.com/zulu/bin/zulu17.28.13-ca-jdk17.0.0-linux_x64.tar.gz -o zulu17.28.13-ca-jdk17.0.0-linux_x64.tar.gz
  - gunzip zulu17.28.13-ca-jdk17.0.0-linux_x64.tar.gz
  - tar -xvf zulu17.28.13-ca-jdk17.0.0-linux_x64.tar
  - export PATH="$PATH:/tmp/zulu17.28.13-ca-jdk17.0.0-linux_x64/bin"
  - java --version
  - export JAVA_HOME="/tmp/zulu17.28.13-ca-jdk17.0.0-linux_x64"
  - curl https://dlcdn.apache.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz -o apache-maven-3.8.2-bin.tar.gz
  - gunzip apache-maven-3.8.2-bin.tar.gz
  - tar -xvf apache-maven-3.8.2-bin.tar
  - export PATH="$PATH:/tmp/apache-maven-3.8.2/bin"
  - mvn --version
  - cd "$WORK_DIR"
  - echo "running"
  - make

cache:
  directories:
    - $HOME/.m2
