micronaut:
  application:
    name: iam
  executors:
    io:
      type: fixed
      n-threads: 5

grpc:
  server:
    port: 50500
    keep-alive-time: 3h
    max-inbound-message-size: 4096

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/iam
    driverClassName: org.postgresql.Driver
    username: user
    password: "password"
    dialect: postgres
    maximum-pool-size: 2
    connection-test-query: "select 1"

cache:
  redis:
    host: localhost
    port: 6379
    connectionTimeout: 500
    pool:
      maxSize: 4
      idleSize: 2

flyway:
  datasources:
    default:
      enabled: true

jwt:
  secret: "secretsecretsecretsecretsecretsecretsecretsecret"
  token:
    lifetime: 30
  refresh_token:
    lifetime: 300
